FROM golang:1.19

RUN apt-get update && apt-get install ruby vim-common -y

RUN apt-get install flex bison -y
RUN wget http://www.tcpdump.org/release/libpcap-1.10.0.tar.gz && tar xzf libpcap-1.10.0.tar.gz && cd libpcap-1.10.0 && ./configure && make install

ENV GOPROXY='https://goproxy.cn,direct'

RUN go install golang.org/x/lint/golint@latest

ENV GOR_SRC="/go/src/github.com/buger/goreplay/"

WORKDIR $GOR_SRC
ADD . $GOR_SRC

RUN go get